//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public album()
        {
            this.comment_album = new HashSet<comment_album>();
            this.songs = new HashSet<song>();
            this.upload_album = new HashSet<upload_album>();
        }
    
        public int album_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public string album_name { get; set; }
        public Nullable<System.DateTime> album_createdate { get; set; }
        public string album_image { get; set; }
        public Nullable<int> album_view { get; set; }
        public Nullable<int> album_viewed_day { get; set; }
        public Nullable<int> album_viewed_week { get; set; }
        public Nullable<int> album_viewed_month { get; set; }
    
        public virtual author author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment_album> comment_album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<song> songs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upload_album> upload_album { get; set; }
    }
}
