//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSEntities : DbContext
    {
        public MSEntities()
            : base("name=MSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<comment_album> comment_album { get; set; }
        public virtual DbSet<comment_singer> comment_singer { get; set; }
        public virtual DbSet<comment_song> comment_song { get; set; }
        public virtual DbSet<genre> genres { get; set; }
        public virtual DbSet<singer> singers { get; set; }
        public virtual DbSet<song> songs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<upload_album> upload_album { get; set; }
        public virtual DbSet<upload_song> upload_song { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
