//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class singer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public singer()
        {
            this.comment_singer = new HashSet<comment_singer>();
            this.songs = new HashSet<song>();
        }
    
        public int singer_id { get; set; }
        public string singer_name { get; set; }
        public string singer_nickname { get; set; }
        public bool singer_sex { get; set; }
        public string singer_country { get; set; }
        public string singer_image { get; set; }
        public string singer_cover_image { get; set; }
        public Nullable<System.DateTime> singer_dateofbirth { get; set; }
        public string singer_description { get; set; }
        public Nullable<System.DateTime> singer_createdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment_singer> comment_singer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<song> songs { get; set; }
    }
}
