//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class upload_song
    {
        public int user_id { get; set; }
        public int song_id { get; set; }
        public Nullable<System.DateTime> upload_song_date { get; set; }
    
        public virtual song song { get; set; }
        public virtual user user { get; set; }
    }
}
