//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.comment_album = new HashSet<comment_album>();
            this.upload_album = new HashSet<upload_album>();
            this.upload_song = new HashSet<upload_song>();
        }
    
        public int user_id { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Mật khẩu")]
        public string password { get; set; }
        [DisplayName("Họ và tên")]
        public string user_name { get; set; }
        [DisplayName("Ngày sinh")]
        public Nullable<System.DateTime> user_dateofbirth { get; set; }
        [DisplayName("Giới tính")]
        public bool user_sex { get; set; }
        [DisplayName("Địa chỉ")]
        public string user_address { get; set; }
        [DisplayName("Số điện thoại")]
        public Nullable<decimal> user_phone { get; set; }
        [DisplayName("Hình đại diện")]
        public string user_image { get; set; }
        public Nullable<int> user_level { get; set; }
        [DisplayName("Trạng thái")]
        public bool status { get; set; }
        [DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> user_createdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment_album> comment_album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upload_album> upload_album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<upload_song> upload_song { get; set; }
    }
}
